# 00. PyTorch Fundamentals¶

Link: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [34]:
import torch
import os
import time

In [36]:
def stress_test(duration=60):
    print("Iniciando teste de stress....")
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Criação de tensores grandes para usar a memória da GPU
    size = (10000, 10000)
    tensor_a = torch.randn(size, device=device)
    tensor_b = torch.randn(size, device=device)

    # Início do teste de stress
    start_time = time.time()
    while time.time() - start_time < duration:
        # Operações intensivas na GPU
        result = torch.matmul(tensor_a, tensor_b)
        result = torch.sin(result)

        # Para garantir que as operações sejam executadas na GPU
        torch.cuda.synchronize()

    print("Teste de stress concluído.")

In [2]:
torch.__version__

'2.4.0'

In [37]:
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
    print("GPU name: ", torch.cuda.get_device_name(0), " - ", torch.cuda.device_count(), " GPU(s) available.")
    stress_test(60)
else:
    print("CUDA is not available. GPU cannot be used.")

CUDA is available. GPU can be used.
GPU name:  NVIDIA GeForce RTX 3060 Ti  -  1  GPU(s) available.
Iniciando teste de stress....
Teste de stress concluído.


In [4]:

# Check if running on macOS and PyTorch version supports MPS (Metal Performance Shaders)
if torch.backends.mps.is_available() and os.uname().sysname == 'Darwin':
    print("MPS is available. GPU can be used.")
    stress_test(60)
else:
    print("MPS is not available. GPU cannot be used.")

MPS is not available. GPU cannot be used.


## Tensors

### Scalar

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

### Vector

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

### MATRIX

In [9]:
# Check shape of vector
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check number of dimensions
MATRIX.ndim

2

In [23]:
MATRIX.shape

torch.Size([2, 2])

### TENSOR

In [24]:
# Tensor
TENSOR = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [3, 6, 9],
                        [2, 4, 5],
                        [1, 2, 3],
                        [3, 6, 9],
                        [3, 6, 9],
                        [2, 4, 5]
                        ],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [3, 6, 9],
                        [2, 4, 5],
                        [1, 2, 3],
                        [3, 6, 9],
                        [3, 6, 9],
                        [2, 4, 5]
                        ]]
                       ])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [3, 6, 9],
          [2, 4, 5],
          [1, 2, 3],
          [3, 6, 9],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [3, 6, 9],
          [2, 4, 5],
          [1, 2, 3],
          [3, 6, 9],
          [3, 6, 9],
          [2, 4, 5]]]])

In [25]:
# Check number of dimensions for TENSOR
TENSOR.ndim

4

In [26]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 2, 8, 3])

## Random tensors

In [27]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2896, 0.3900, 0.1770, 0.4887],
         [0.0877, 0.7872, 0.9849, 0.5625],
         [0.9198, 0.5673, 0.7233, 0.1546]]),
 torch.float32)

In [28]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Range and tensors like

In [31]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_16752/232764869.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [33]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))